version: '3.8'

services:
  nats-seed:
    image: nats:alpine
    environment:
      - NATS_PORT=4222
      - NATS_HTTP_PORT=8222
      - NATS_CLUSTER_NAME=test-cluster
      - NATS_CLUSTER_PORT=4248
      - NATS_CLUSTER_ROUTES=nats://nats-seed:4248,nats://nats-1:4248
    volumes:
      - ./conf/nats_conf.yaml:/etc/nats/nats-server.conf
    ports:
      - "8080:8222"
  nats-1:
    image: nats:alpine
    environment:
      - NATS_PORT=4222
      - NATS_HTTP_PORT=8222
      - NATS_CLUSTER_NAME=test-cluster
      - NATS_CLUSTER_PORT=4248
      - NATS_CLUSTER_ROUTES=nats://nats-seed:4248,nats://nats-1:4248
    volumes:
      - ./conf/nats_conf.yaml:/etc/nats/nats-server.conf
    depends_on:
      - nats-seed
        